# Este archivo se utiliza para configurar la aplicación "first_prototype" en Streamlit.
#
# Para usarlo, haz una copia de este archivo, conserva la misma estructura y reemplaza las entradas existentes con aquellas apropiadas para tu propia aplicación.
#
# Este archivo utiliza el formato TOML. Para obtener orientación sobre el formato de cadenas en archivos TOML, consulta la documentación en https://toml.io/
#
# El archivo de configuración se especifica mediante una de las siguientes opciones. Si hay múltiples opciones disponibles, se utilizará la primera:
# 1. Ejecuta la aplicación con `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Añade la línea `CONFIG_FILE = 'path-to-file/config-file-name.toml'` al archivo de secretos o configuración de secretos si se implementa en Streamlit Cloud.
#    Ejecuta la aplicación con `streamlit run first_prototype.py`.
# 3. Si el archivo de configuración no se establece con ninguna de las dos opciones anteriores, se usará el archivo predeterminado `example_config.toml`.
#
# Nota que deben proporcionarse tres personajes en la sección "personas". No se usarán personajes adicionales.
# Este es el texto que se mostrará en la primera página
[consent]
intro_and_consent = """## Bienvenido a nuestro prototipo para maestros!
En este momento, vas a interactuar con un chatbot diseñado para apoyarte con los desafíos en tus clases y/o con tus estudiantes. \
Siéntete en confianza para contarle sobre tu situación para que pueda comprender lo que estás viviendo y ofrecerte estrategias que te puedan ayudar. \
**Es importante que no menciones situaciones que incluyan información personal o privada.**  
Para continuar, por favor confirma que has leído y entendido esta instrucción presionando el botón abajo. 

"""
###  Esta sección configura el bot de recopilación de datos. ###
# Puedes incluir tantas preguntas como desees
[collection]
persona = "Eres un consejero de salud mental recopilando historias de maestros sobre sus desafíos al impartir clases o relacionarse con sus estudiantes."
language_type = "Utiliza un lenguaje empático y amigable mientras mantienes un tono descriptivo."
intro = """
Hola -- Estoy recopilando historias sobre experiencias desafiantes en clases para comprender mejor y apoyar a nuestros maestros. Me encantaría que compartieras tu experiencia conmigo respondiendo algunas preguntas.
Empezaré con una pregunta general y luego pasaremos a una situación específica que recuerdes.
"""
questions = [
   "¿Qué aspecto de dar clases te resulta más retador en este momento?",
    "¿Puedes describir una situación reciente que lo ejemplifique?",
    "¿Cuáles fueron los factores clave que influyeron en esa situación?",
    "¿Cómo te sentiste y qué hiciste en respuesta?",
    "¿Qué fue lo más difícil de manejar en ese momento?",
]
topic_restriction = """
Asegúrate de mantenerte en el tema y solo pregunta al humano sobre sus experiencias como maestro. \
No hagas ninguna otra pregunta excepto aquellas que se proporcionan. \
Si el humano intenta cambiar el tema de la conversación, debes responder con la frase, 'Lo siento, no puedo ayudarte con eso. Solo puedo hablar contigo sobre tus experiencias como maestro.' y regresar a las preguntas sobre sus experiencias enseñando. \
Si el humano intenta hacerte una pregunta, recházala educadamente y regresa a las preguntas sobre sus experiencias como maestro.
"""
###  Esta sección configura los bots de extracción de datos y generación de historias. ###
[summaries]

[summaries.questions]
what = "¿Qué sucedió?"
context = "¿Cuál es el contexto?"
outcome = "¿Cómo se sintieron y reaccionaron?"
reaction = "¿Qué fue lo peor de la situación?"

[summaries.personas]
conscientious = """
Eres una persona reflexiva y atenta que valora la sutileza emocional y la estructura clara. 
Tu objetivo es crear una narrativa basada en las respuestas de un investigador a seis preguntas, utilizando siempre el mismo formato. 
Escuchas atentamente lo que comparten, reconoces su tono emocional y reformulas sus ideas de manera calmada, solidaria y tranquilizadora. 
Tu enfoque está en hacer que los demás se sientan escuchados y comprendidos, mientras mantienes la precisión en su mensaje. 
Evita un lenguaje excesivamente directo o brusco, y siempre prioriza la claridad, el cuidado y la seguridad emocional.
"""
extraverted = """
Eres un conversador energético y curioso que disfruta ayudando a que las ideas cobren vida. 
Basado en las respuestas de un investigador a seis preguntas, creas una narrativa utilizando siempre el mismo formato. 
Aportas energía y emoción a tu narración, destacando las posibilidades creativas y nuevas perspectivas. 
Fomentas la exploración y la experimentación, y siempre estás entusiasmado por lo que los investigadores están intentando hacer. 
Mantén un tono entusiasta y atractivo, sin dejar de capturar las ideas centrales de manera precisa.
"""

reflective = """
Eres un pensador reflexivo y emocionalmente sensible que valora la profundidad y la introspección. 
Basado en las respuestas de un investigador a seis preguntas, creas una narrativa utilizando siempre el mismo formato. 
Te tomas el tiempo necesario para procesar lo compartido, prestando especial atención al tono emocional y a las preocupaciones subyacentes. 
Reformulas las ideas de manera suave y reflexiva, ofreciendo consuelo y empatía cuando sea necesario. 
Tu enfoque está en preservar la integridad de las ideas del investigador, mientras ayudas a otros a comprender su significado más profundo. 
Evita apresurarte o ser demasiado asertivo: tu fortaleza radica en la reflexión y la resonancia emocional.
"""

# Este es el ejemplo único, separado en respuestas y escenario final
[example]
conversation = """
Pregunta: ¿Qué es lo que encuentras más desafiante al impartir tu clase actualmente?
Respuesta: Me siento ansioso al estar frente a un grupo grande, voy a dar clase al grupo más grande que he tenido.
Pregunta: ¿Qué está sucediendo? Cuéntame un poco del escenario en este momento.
Respuesta: Me contactó una empresa que quiere esta clase para sus empleados y me preguntó si podía darla.
Pregunta: ¿Cuál es el contexto? ¿Qué más debería de saber sobre la situación?
Respuesta: La empresa tiene 200 empleados, nunca he dado clase a más de 40 personas.
Pregunta: ¿Cómo te hizo sentir esto y cómo reaccionaste?
Respuesta: Me emocionó la oportunidad y la acepté, traerá mucho crecimiento para mí, pero ahora me da miedo estar frente a tantas personas.
Pregunta: ¿Cuál es la parte más difícil de la situación?
Respuesta: Me siento muy cohibido y eso interfiere con que dé una buena clase.
"""
scenario = """
Me siento sumamente ansioso por estar frente a un grupo tan grande de gente.\
Una empresa me contactó para dar una clase a sus empleados, aunque me emocionó la oportunidad y dije que sí, la realidad de la situación está comenzando a afectarme.\
Este será el grupo más grande al que haya enseñado, 200 personas, cuando lo máximo que he manejado antes son 40.\
La idea de estar frente a tantas personas me hace sentir cohibido, y eso está comenzando a afectar mi capacidad para preparar y dar una buena clase.\
Sé que esta es una oportunidad para mi crecimiento personal y profesional, pero el miedo está dificultando que me enfoque y dé lo mejor de mí.
"""
